name: MLflow CI Workflow Obesity - Category

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mlflow-run:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Environment Variables
        run: |
          echo "MLFLOW_TRACKING_USERNAME is set: ${{ secrets.MLFLOW_TRACKING_USERNAME != '' }}"
          echo "MLFLOW_TRACKING_PASSWORD is set: ${{ secrets.MLFLOW_TRACKING_PASSWORD != '' }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MLproject/requirements.txt
      - name: Run MLflow project
        run: |
          mlflow run MLproject --env-manager=local

      - name: Get latest MLflow run ID
        run: |
          echo "Using default experiment (ID 0)..."
          RUN_ID=$(mlflow runs list --experiment-id 0 --order-by start_time DESC | awk 'NR==2 {print $1}')
          echo "Latest run ID: $RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
