name: MLflow CI Workflow Obesity - Category

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mlflow-run:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          echo "MLFLOW_TRACKING_USERNAME is set: ${{ secrets.MLFLOW_TRACKING_USERNAME != '' }}"
          echo "MLFLOW_TRACKING_PASSWORD is set: ${{ secrets.MLFLOW_TRACKING_PASSWORD != '' }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MLproject/requirements.txt
      - name: Run MLflow project
        run: |
          mlflow run MLproject --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          echo "Getting latest run ID..."
          python <<EOF
          import mlflow
          client = mlflow.tracking.MlflowClient()
          runs = client.search_runs(experiment_ids=["0"], order_by=["start_time DESC"]) 
          run_id = runs[0].info.run_id
          print(f"Latest run ID: {run_id}")
          with open("${{ github.env }}", "a") as f:
              f.write(f"RUN_ID={run_id}\n")
          EOF

      - name: Download model artifacts from DagsHub
        run: |
          echo "Downloading model artifact for run: $RUN_ID"
          mlflow artifacts download --run-id $RUN_ID --artifact-path model -d ./downloaded
          mv ./downloaded/model ./best_model

      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri ./best_model --name obesity-model 

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Tag Docker Image
        run: |
          docker tag obesity-model ${{ secrets.DOCKER_USERNAME }}/obesity-model:latest
          

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/obesity-model:latest
